---

## Ansible scripts for https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

- name: Add an kuberntes Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present


- name: Add kuberntes repository into sources list
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes


- name: Update repositories cache
  apt:
    update_cache: yes


- name: Install kuberntes components
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes



# Task is specific to running kuberenetes cluster on VM's on a single host
# kubelet needs to be assiged a node-ip without which kubernetes inter node
#communicaiton fails
- name: Configure the kubelet
  shell: |
    sed -i '5 a Environment="KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}"' \
                /etc/systemd/system/kubelet.service.d/10-kubeadm.conf


- name: Make sure a kubelet service is running
  systemd:
    state: restarted
    name: kubelet
    daemon_reload: yes
    enabled: yes
