# api server parameters
#–service-node-port-range portRange     Default: 30000-32767
#–advertise-address ip
---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster


- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init  \
            --pod-network-cidr {{ pod_network_cidr }} \
                 --token {{ token }}  \
                 --apiserver-advertise-address {{ apiserver_advertise_address }} \
                --apiserver-cert-extra-sans {{ apiserver_cert_extra_sans }}
  register: init_cluster


- name: Taint Master sowe can deploy here
  when: init_cluster is succeeded
  shell: |
    kubectl --kubeconfig /etc/kubernetes/admin.conf \
                  taint nodes --all node-role.kubernetes.io/master-
  register: taint_cluster



- name: Apply CNI to cluster
  when: taint_cluster is succeeded
  shell: |
    kubectl --kubeconfig /etc/kubernetes/admin.conf \
                    apply -f  {{cni_url}}
  register: cni_cluster




  ## Ideally Wait for CoreDns pods to be running before jumping into adding workers


- name: Extract discovery-token-ca-cert-hash for cluster
  when: cni_cluster is succeeded
  shell: |
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | \
              openssl rsa -pubin -outform der 2>/dev/null | \
                      openssl dgst -sha256 -hex | sed 's/^.* //' \
                            > /vagrant_data/discovery.hash
  register: dicovery_token
